### ISSUE TITLE
Crash on startup (Ubuntu)

### ISSUE THREAD

**Issue by gogogoluke1** [AurousGroup/frontend#42]
Here is the error:

Exception in Application start method
Oct 15, 2015 2:02:41 PM me.aurous.launchwrapper.Updater main
SEVERE: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at me.aurous.launchwrapper.AurousLoader.launchAurous(AurousLoader.java:39)
	at me.aurous.launchwrapper.Updater.main(Updater.java:32)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$156(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: Failed to start IPC process.
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
	... 1 more
Caused by: java.lang.RuntimeException: java.io.IOException: Cannot run program "/home/gogogoluke/Documents/linux/jxbrowser-chromium" (in directory "/home/gogogoluke/Documents/linux"): error=13, Permission denied
	at com.teamdev.jxbrowser.chromium.internal.ipc.ChromiumProcess.start(Unknown Source)
	... 2 more
Caused by: java.io.IOException: Cannot run program "/home/gogogoluke/Documents/linux/jxbrowser-chromium" (in directory "/home/gogogoluke/Documents/linux"): error=13, Permission denied
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	... 3 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 3 more

Exception in thread "Thread-7" java.lang.NullPointerException
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.c(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.b(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.IPC.a(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.b.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by roipoussiere** [comment]
Same problem on Linux Mint 17.1 with Awesome WM, with Java 8 up to date. Idem when launching with sudo.
